### ISSUE TITLE
Failed test 'standard timestamp' while installing via zef

### ISSUE THREAD

**Issue by masukomi** [whity/raku-log#4]
```
❯ zef install Logger
[ snipped updating repos ]
===> Testing: Logger:ver<0.4.5>
[Logger] # Failed test 'standard timestamp'
[Logger] # at t/06-datetime-formatter.t line 21
[Logger] # expected a match with: /^ '[' \d+ '-' \d+ '-' \d+ 'T' \d+ ':' \d+ ':' \d+ '.' \d+ 'Z'? ']'/
[Logger] #                   got: "[2022-10-19T23:11:21.125743-04:00][INFO] test message\n"
[Logger] # You failed 1 test of 2
===> Testing [FAIL]: Logger:ver<0.4.5>
Aborting due to test failure: Logger:ver<0.4.5> (use --force-test to override)
```

OS: macOS Monterrey v 12.6 on m1 mac.
```
❯ rakudo --version
Welcome to Rakudo™ v2022.07.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.07.
```

**Comment by whity** [comment]
@masukomi thank you for the report, should be fixed.

**Comment by masukomi** [comment]
a) yay
b) i don't think the update went to zef correctly. it says it was updated "a day ago" but it's still saying 0.4.5 and when i trying uninstalling and reinstalling it's still the most recent one and still failing. 

I suspect this is related to zef caching old versions so that we don't have a left-pad incident. Prolly needs to have the version bumped in `META6.json` to 0.4.6 (or whatever) for us to get the changes.

**Comment by demanuel** [comment]
@whity Can you please bump the version in META6.json file and then upload it to fez?

Thanks!

**Comment by whity** [comment]
@demanuel i was about to upload it, but seems it's already there.
thanks

**Comment by whity** [comment]
@demanuel sorry, it wasn't there yet, just uploaded it, everything should be fine now, thanks.

**Comment by demanuel** [comment]
@whity Thank you! It's now working without issues! :-D
